import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './layout.module.css'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const user = { firstName: 'BonjourLesPixels' }

interface IRootLayout {
    children: React.ReactNode
}

export default function RootLayout({ children }: IRootLayout) {
    return (
        <html lang="en">
            <body className={`${inter.className} ${styles.layout_container}`}>
                <Header user={user} />
                {children}
            </body>
        </html>
    )
}
